updated to PM4
GamakCZ/SkyWars pull request #84
Opened 2022-02-19 13:00 UTC by xxFLORII

2022-05-29 07:29 UTC, VixikHD requested changes
I like this pr so far! Just need a few changes in order to release update

2022-05-29 07:29 UTC, VixikHD commented on SkyWars/plugin.yml
>  version: 1.2.1
```suggestion
version: 1.3.0-beta1
```

2022-05-29 07:29 UTC, VixikHD commented on SkyWars/plugin.yml
>  version: 1.2.1
In order to update plugin on poggit it is required to increase the version

2022-05-29 07:29 UTC, VixikHD commented on SkyWars/src/vixikhd/skywars/arena/ArenaScheduler.php
> +        if(!$signPos->getWorld() instanceof World || is_null($this->plugin->level)) return;
Position->getWorld() no longer returns null and is always of World instance
```suggestion
        if(!$signPos->getWorld()->isLoaded() || is_null($this->plugin->level)) return;
```

2022-05-29 07:30 UTC, VixikHD commented on SkyWars/plugin.yml
>  version: 1.2.1
Also you should mention yourself in authors field

2023-04-03 14:26 UTC, Smorted approved these changes

2023-04-10 20:25 UTC, xxFLORII commented
Sorry for the late answer, i will add the requested changes tomorrow.

2025-07-21 20:58 UTC, closed without merging